"""empty message

Revision ID: 31bef421a267
Revises: bb50bb20d556
Create Date: 2022-05-02 11:27:01.096463

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '31bef421a267'
down_revision = 'bb50bb20d556'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('characters_ibfk_1', 'characters', type_='foreignkey')
    op.drop_column('characters', 'favorites_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('favorites_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('characters_ibfk_1', 'characters', 'favorites', ['favorites_id'], ['id'])
    # ### end Alembic commands ###
