"""empty message

Revision ID: 78a129a7d5dc
Revises: ce0476b9cdc1
Create Date: 2022-05-03 09:21:28.179690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78a129a7d5dc'
down_revision = 'ce0476b9cdc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'planets', ['name'])
    op.create_unique_constraint(None, 'vehicles', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicles', type_='unique')
    op.drop_constraint(None, 'planets', type_='unique')
    # ### end Alembic commands ###
