"""empty message

Revision ID: ce0476b9cdc1
Revises: 31bef421a267
Create Date: 2022-05-02 13:19:58.138879

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ce0476b9cdc1'
down_revision = '31bef421a267'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('character_id', sa.Integer(), nullable=True))
    op.add_column('favorites', sa.Column('planet_id', sa.Integer(), nullable=True))
    op.add_column('favorites', sa.Column('vehicle_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'favorites', 'vehicles', ['vehicle_id'], ['id'])
    op.create_foreign_key(None, 'favorites', 'planets', ['planet_id'], ['id'])
    op.create_foreign_key(None, 'favorites', 'characters', ['character_id'], ['id'])
    op.drop_constraint('planets_ibfk_1', 'planets', type_='foreignkey')
    op.drop_column('planets', 'favorites_id')
    op.drop_constraint('vehicles_ibfk_1', 'vehicles', type_='foreignkey')
    op.drop_column('vehicles', 'favorites_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('favorites_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('vehicles_ibfk_1', 'vehicles', 'favorites', ['favorites_id'], ['id'])
    op.add_column('planets', sa.Column('favorites_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('planets_ibfk_1', 'planets', 'favorites', ['favorites_id'], ['id'])
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.drop_column('favorites', 'vehicle_id')
    op.drop_column('favorites', 'planet_id')
    op.drop_column('favorites', 'character_id')
    # ### end Alembic commands ###
