"""empty message

Revision ID: f84a1b44369d
Revises: 778b06baac2b
Create Date: 2022-05-02 11:21:20.904121

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f84a1b44369d'
down_revision = '778b06baac2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'characters', ['name'])
    op.drop_constraint('characters_ibfk_1', 'characters', type_='foreignkey')
    op.drop_column('characters', 'favorites_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('favorites_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('characters_ibfk_1', 'characters', 'favorites', ['favorites_id'], ['id'])
    op.drop_constraint(None, 'characters', type_='unique')
    # ### end Alembic commands ###
